excluded:
  - Carthage
  - TRiOS/GraphQL
  - Tarradiddle.playground

identifier_name:
  severity: warning
  excluded:
    - id
    - db
    - vc
    - t

force_try: warning

opt_in_rules:
  - vertical_parameter_alignment_on_call
  - unavailable_function
  - redundant_type_annotation
  - quick_discouraged_pending_test
  - quick_discouraged_focused_test
  - quick_discouraged_call
  - prohibited_super_call
  - overridden_super_call
  - operator_usage_whitespace
  - object_literal
  - number_separator
  - nimble_operator
  - multiline_parameters
  - multiline_function_chains
  - multiline_arguments
  - modifier_order
  - implicitly_unwrapped_optional
  - implicit_return
  - function_default_parameter_at_end
  - force_unwrapping
  - convenience_type
  - closure_spacing
  - closure_end_indentation
